{% set name = "azure-mgmt-containerregistry" %}
{% set version = "8.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: f2bcdbcf0b9fdc2df0df9eccb77cb489091d3c670ed53cba77e5ffd734e9539b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - msrest >=0.6.21
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.2.0,<2.0.0

test:
  imports:
    - azure.mgmt.containerregistry
    - azure.mgmt.containerregistry.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Container Registry Client Library for Python

  doc_url: https://docs.microsoft.com/en-us/python/api/overview/azure/container-registry
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - awvwgk
    - andreyz4k
