travis:
  secure:
    BINSTAR_TOKEN: Z/qpx+CHfz8LbBNAB6FSpVWSQhpD41mo/HPfrfSL1iezqncAi7ET6CKQax90vEpAlVv4pkWLudXPL1G1DMPOX/U+1HIrsVWL0B+SRQWefUozmsPl7nMUOsOs2wAYUjdw4rWTe+avOiZ+stnTlsg6qE8BuWguLrPRZEpzGegU8Bd4AYweN5XXH0in0HF1cKdeMJaPExdEMNTtn3tCZYmONHNF/epXawyFGkzX7ZfZvw/v3/iaJjlhPeHlhEPli4c60NC+HxzM58sktYMH+pkfifgFzq/9MRTAkPpK7OX92pftbs+UjuNBXA78VQcxLeTJeZtJ54c3HMSWSQ1zXoXalfBqDS3eURPiC6TGY3xv6l1fti8ruw0goCBTIaSCvv9qOHwHONWv9ax0BlgAKUflaEtjUR9LtqsvNPgJ/Up5EKJPclZ/0nVyDYpDoD4lOrbjkgAwmwEBqY8BmikY8ymTE3oDW8ORq3HOGgBMHefAxApS6piHp5rT41nfMj4lSoaeVA6Td6Elun2HuMnVQWMBRQQjS60AlPR0gTSigNBd2VtLHrUbM1WcqFUHRFG1scVX6feeriRXKqx+ZIw0u6ayHN5v0cqzUNeV3fBXaU1Va7deW7m1ps1IO3UBOeIKcNLkN2cDJz980PTZ6unjnlj1c7TcpWW2txD729TFG9kq0wI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
